-- Exports the database schema as one statement per row (read-only).
-- Run in the Supabase SQL Editor, then Export -> Download CSV and save as
-- supabase/schema-export.csv. Used to build the baseline migration and to
-- compare databases (e.g. the local test copy with the live project).
with
ext as (
  select 10 as ord, e.extname as obj,
         format('create extension if not exists %I with schema %I;', e.extname, n.nspname) as ddl
  from pg_extension e join pg_namespace n on n.oid = e.extnamespace
  where e.extname <> 'plpgsql'
),
enums as (
  select 20, t.typname,
         format('create type public.%I as enum (%s);', t.typname,
                string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder))
  from pg_type t
  join pg_namespace n on n.oid = t.typnamespace
  join pg_enum e on e.enumtypid = t.oid
  where n.nspname = 'public'
  group by t.typname
),
seqs as (
  select 30, s.sequencename,
         format('create sequence if not exists public.%I;', s.sequencename)
  from pg_sequences s
  where s.schemaname = 'public'
),
tables as (
  select 40, c.relname,
         format(E'create table public.%I (\n%s\n);', c.relname,
           string_agg(
             format('  %I %s', a.attname, format_type(a.atttypid, a.atttypmod))
             || case when a.attidentity = 'a' then ' generated always as identity'
                     when a.attidentity = 'd' then ' generated by default as identity'
                     else '' end
             || case when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
                     when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid)
                     else '' end
             || case when a.attnotnull then ' not null' else '' end,
             E',\n' order by a.attnum))
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind in ('r', 'p')
  group by c.relname
),
cons as (
  select case when con.contype = 'f' then 60 else 50 end, rel.relname || '.' || con.conname,
         format('alter table public.%I add constraint %I %s;', rel.relname, con.conname, pg_get_constraintdef(con.oid))
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public' and con.contype in ('p', 'u', 'c', 'f', 'x')
),
idx as (
  select 70, i.indexname, i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and i.indexname not in (select conname from pg_constraint)
),
funcs as (
  select 80, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         pg_get_functiondef(p.oid) || ';'
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
),
views as (
  select 90, c.relname,
         format(E'create or replace view public.%I%s as\n%s', c.relname,
                coalesce(' with (' || array_to_string(c.reloptions, ', ') || ')', ''),
                pg_get_viewdef(c.oid, true))
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'v'
),
trg as (
  select 100, c.relname || '.' || t.tgname, pg_get_triggerdef(t.oid, true) || ';'
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where not t.tgisinternal and (n.nspname = 'public' or (n.nspname = 'auth' and c.relname = 'users'))
),
rls as (
  select 110, c.relname, format('alter table public.%I enable row level security;', c.relname)
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p') and c.relrowsecurity
),
pol as (
  select 120, p.schemaname || '.' || p.tablename || '.' || p.policyname,
         format('create policy %I on %I.%I as %s for %s to %s%s%s;',
                p.policyname, p.schemaname, p.tablename, lower(p.permissive), lower(p.cmd),
                array_to_string(p.roles, ', '),
                coalesce(' using (' || p.qual || ')', ''),
                coalesce(' with check (' || p.with_check || ')', ''))
  from pg_policies p
  where p.schemaname in ('public', 'storage')
),
table_grants as (
  select 130, c.relname,
         format('revoke all on public.%I from anon, authenticated, service_role;', c.relname)
         || coalesce(E'\n' || string_agg(
              format('grant %s on public.%I to %s;', g.privilege_type, c.relname, r.rolname),
              E'\n' order by r.rolname, g.privilege_type), '')
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  left join lateral aclexplode(coalesce(c.relacl, acldefault('r', c.relowner))) g on true
  left join pg_roles r on r.oid = g.grantee and r.rolname in ('anon', 'authenticated', 'service_role')
  where n.nspname = 'public' and c.relkind in ('r', 'p', 'v')
    and (r.rolname is not null or g.grantee is null)
  group by c.relname
),
func_grants as (
  select 140, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         format('revoke all on function public.%I(%s) from public, anon, authenticated;',
                p.proname, pg_get_function_identity_arguments(p.oid))
         || coalesce(E'\n' || string_agg(
              format('grant execute on function public.%I(%s) to %s;', p.proname,
                     pg_get_function_identity_arguments(p.oid),
                     case when g.grantee = 0 then 'public' else r.rolname end),
              E'\n' order by case when g.grantee = 0 then 'public' else r.rolname end), '')
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  left join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) g on true
  left join pg_roles r on r.oid = g.grantee
  where n.nspname = 'public' and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
    and (g.grantee = 0 or r.rolname in ('anon', 'authenticated', 'service_role'))
  group by p.oid, p.proname
),
buckets as (
  select 150, b.id,
         format('insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values (%L, %L, %s, %s, %s) on conflict (id) do nothing;',
                b.id, b.name, case when b.public then 'true' else 'false' end,
                coalesce(b.file_size_limit::text, 'null'),
                coalesce(quote_literal(b.allowed_mime_types::text) || '::text[]', 'null'))
  from storage.buckets b
),
categories_data as (
  select 160, c.slug,
         format('insert into public.categories (id, slug, name, sort_order) values (%L, %L, %L::jsonb, %s) on conflict (id) do nothing;',
                c.id, c.slug, c.name::text, c.sort_order)
  from public.categories c
)
select ord, obj as object, ddl from (
  select * from ext union all select * from enums union all select * from seqs
  union all select * from tables union all select * from cons union all select * from idx
  union all select * from funcs union all select * from views union all select * from trg
  union all select * from rls union all select * from pol union all select * from table_grants
  union all select * from func_grants union all select * from buckets union all select * from categories_data
) all_ddl (ord, obj, ddl)
order by ord, obj;
